### PR TITLE
Add Numeric rule

### LINKED ISSUE #55: New Rule: IsNumeric
Rule to validate data to be numeric.
if its string checks with builtin `isnumeric()` else check for types int, float, complex

Description: "The field under validation must be numeric"

### PR DESCRIPTION
**Pull request by bsoyka**
Closes #55.

### CODE REVIEW

**Comment by CSenshi** [comment]
It seems `isnumeric()` is not what we really need. There is new commit in the master branch which includes util functions in `vlidator/utils.py` it can be helpful for this task :)

**Comment by iko1133** [comment]
Hey @bsoyka , are you still up for this?

**Comment by bsoyka** [comment]
You can take it if you'd like, @iko1133. If you want it I'll close up this PR.

**Comment by iko1133** [comment]
If you are not going to finish it, I'll take it :)

**Comment by bsoyka** [comment]
Go for it! Closing this now.

**Pull request closed without merging**
